[global]
# Optimized for Streamlit Cloud deployment
developmentMode = false
showWarningOnDirectExecution = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

[runner]
# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
magicEnabled = true

[server]
# Production server settings
runOnSave = false
address = "0.0.0.0"
port = 8501
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser settings for deployment
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501

[theme]
# Custom theme matching the app design
primaryColor = "#28a745"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"
font = "sans serif"

[client]
# Client optimization settings
displayEnabled = true
showErrorDetails = false
toolbarMode = "viewer"

